export type Lang = 'nb' | 'en';

export const STRINGS = {
  nb: {
    appName: 'Antidoping',
    tagline: 'i lomma',
    home_hello: 'Hei, Emma',
    home_sub: 'Hva trenger du hjelp til i dag?',
    home_features: {
      risk: 'Kosttilskudd',
      medicine: 'Legemidler',
      wada: 'Dopinglista',
      messages: 'Meldinger',
      learn: 'Ren Utøver',
      exemption: 'Fritak',
      asthma: 'Astma',
      report: 'Varsle',
      contact: 'Spør ADNO',
    },
    onboard: {
      welcome_title: 'Velkommen til Antidoping',
      welcome_sub: 'Alt du trenger for å ta trygge valg — samlet på ett sted.',
      continue: 'Kom i gang',
      role_title: 'Hvem er du?',
      role_sub: 'Vi tilpasser innholdet etter rollen din.',
      role_athlete: 'Utøver',
      role_athlete_sub: 'Konkurranse eller bredde',
      role_coach: 'Trener / støtteapparat',
      role_coach_sub: 'Ansvar for andre utøvere',
      role_parent: 'Foresatt',
      role_parent_sub: 'Forelder eller verge',
      consent_title: 'Varsler og personvern',
      consent_sub: 'Du kan skru av hver kategori senere.',
      consent_push: 'Viktige varsler fra ADNO',
      consent_push_sub: 'Regelendringer og hastevarsler',
      consent_privacy: 'Jeg godtar personvernerklæringen',
      consent_privacy_sub: 'WADA ISPPPI-kompatibel · Les mer',
      finish: 'Ferdig',
    },
    risk: {
      intro_title: 'Sjekk et kosttilskudd',
      intro_sub: 'Svar på 8 korte spørsmål. Vi gir deg en risikoscore på under ett minutt.',
      intro_cta: 'Begynn sjekk',
      intro_scan: 'Skann strekkode',
      step_of: (a: number, b: number) => `Spørsmål ${a} av ${b}`,
      yes: 'Ja', no: 'Nei', unsure: 'Usikker', next: 'Neste', back: 'Forrige',
      calculating: 'Beregner risiko',
      calc_sub: 'Vi vekter svarene dine mot WADAs prohibited list.',
      result_low_title: 'Lav risiko',
      result_low_sub: 'Produktet ser trygt ut å bruke. Følg anbefalt dose.',
      result_mid_title: 'Middels risiko',
      result_mid_sub: 'Vi anbefaler å bekrefte med ADNO før bruk.',
      result_high_title: 'Høy risiko',
      result_high_sub: 'Dette produktet bør unngås. Vi anbefaler å kontakte ADNO.',
      contact_adno: 'Kontakt ADNO for råd',
      new_check: 'Ny sjekk',
      save_result: 'Lagre til profilen',
    },
    meds: {
      title: 'Legemiddelsøk',
      placeholder: 'Søk på medisin eller virkestoff',
      empty_hint: 'Søk på navn (f.eks. Paracet), virkestoff eller reseptnummer.',
      source: 'Kilde · Felleskatalogen',
      status_allowed: 'Tillatt',
      status_banned: 'Forbudt',
      status_incomp: 'Forbudt i konkurranse',
      status_tue: 'Krever medisinsk fritak',
      send_confirm: 'Send bekreftelse til e-post',
      confirm_sent: 'Bekreftelse sendt',
    },
    wada: {
      title: 'Søk i dopinglista',
      sub: 'WADA Prohibited List · Oppdatert 01.01.2026',
      placeholder: 'Søk på substans eller kategori',
      no_result: 'Ingen treff',
      no_result_sub: 'Vi fant ikke denne substansen. Send oss spørsmålet ditt.',
      ask_adno: 'Spør ADNOs medisinske rådgiver',
      category: 'WADA-kategori',
    },
    messages: { title: 'Meldinger', empty: 'Ingen nye meldinger', mark_read: 'Marker som lest' },
    asthma: {
      title: 'Astmakalkulator',
      sub: 'Sjekk tillatte doser for astmamedisiner.',
      select_med: 'Velg medisin',
      dose: 'Dose (µg)',
      frequency: 'Doser per døgn',
      calc: 'Beregn',
      allowed: 'Innenfor tillatt grense',
      allowed_sub: 'Du trenger ikke medisinsk fritak.',
      needs_tue: 'Krever medisinsk fritak',
      needs_tue_sub: 'Daglig dose overskrider WADAs grenseverdi.',
      goto_tue: 'Les om medisinsk fritak',
    },
    tue: {
      title: 'Medisinsk fritak',
      sub: 'Veileder for deg som trenger å bruke forbudt substans av medisinske grunner.',
    },
    report: {
      title: 'Dopingvarsel',
      sub: 'Varsle om brudd — helt anonymt hvis du ønsker.',
      body: 'Varslingskanalen driftes eksternt av Whistleblower Network. Du kan varsle helt anonymt.',
      cta: 'Gå til anonymt varsel',
      secure: 'Sikker forbindelse',
    },
    contact: {
      title: 'Kontakt oss',
      chat_open: 'Chatten er åpen',
      chat_closed: 'Chatten er stengt · Send beskjed',
      hours: 'Mandag–fredag · 09–15',
      form_name: 'Navn',
      form_email: 'E-post',
      form_message: 'Hva kan vi hjelpe med?',
      send: 'Send melding',
    },
    settings: {
      title: 'Innstillinger',
      profile: 'Profil', push: 'Varsler', privacy: 'Personvern',
      language: 'Språk', about: 'Om appen', signout: 'Logg ut',
      version: 'Versjon 1.0 (beta)',
    },
  },
  en: null as any,
};

// English overrides — covers Home, settings, and tab labels for demo
STRINGS.en = {
  ...STRINGS.nb,
  appName: 'Antidoping',
  tagline: 'in your pocket',
  home_hello: 'Hi, Emma',
  home_sub: 'What can we help with today?',
  home_features: {
    risk: 'Supplements',
    medicine: 'Medicines',
    wada: 'Prohibited list',
    messages: 'Alerts',
    learn: 'Clean Athlete',
    exemption: 'TUE',
    asthma: 'Asthma',
    report: 'Report',
    contact: 'Ask ADNO',
  },
  settings: {
    title: 'Settings',
    profile: 'Profile', push: 'Notifications', privacy: 'Privacy',
    language: 'Language', about: 'About', signout: 'Sign out',
    version: 'Version 1.0 (beta)',
  },
};

export const T = (lang: Lang) => STRINGS[lang] || STRINGS.nb;
