export type Lang = 'nb' | 'en';

export const STRINGS = {
  nb: {
    appName: 'Antidoping',
    tagline: 'i lomma',
    home_hello: 'Hei, Emma',
    home_sub: 'Hva trenger du hjelp til i dag?',
    home_org: 'Antidoping Norge',
    home_quote: '«Sjekk først. Konkurrer rent.»',
    home_features: {
      risk: 'Kosttilskudd',
      medicine: 'Legemidler',
      wada: 'Dopinglista',
      messages: 'Meldinger',
      learn: 'Ren Utøver',
      exemption: 'Fritak',
      asthma: 'Astma',
      report: 'Varsle',
      contact: 'Spør ADNO',
    },
    common: {
      get_started: 'Kom i gang',
      next: 'Neste',
      finish: 'Fullfør',
      cancel: 'Avbryt',
      ok: 'OK',
    },
    onboard: {
      welcome_title: 'Velkommen til Antidoping',
      welcome_sub: 'Alt du trenger for å ta trygge valg — samlet på ett sted.',
      continue: 'Kom i gang',
      role_title: 'Hvem er du?',
      role_sub: 'Vi tilpasser innholdet etter rollen din.',
      role_athlete: 'Utøver',
      role_athlete_sub: 'Konkurranse eller bredde',
      role_coach: 'Trener / støtteapparat',
      role_coach_sub: 'Ansvar for andre utøvere',
      role_parent: 'Foresatt',
      role_parent_sub: 'Forelder eller verge',
      consent_title: 'Varsler og personvern',
      consent_sub: 'Du kan skru av hver kategori senere.',
      consent_push: 'Viktige varsler fra ADNO',
      consent_push_sub: 'Regelendringer og hastevarsler',
      consent_privacy: 'Jeg godtar personvernerklæringen',
      consent_privacy_sub: 'WADA ISPPPI-kompatibel · Les mer',
      finish: 'Ferdig',
    },
    risk: {
      intro_title: 'Sjekk et kosttilskudd',
      intro_sub: 'Svar på 8 korte spørsmål. Vi gir deg en risikoscore på under ett minutt.',
      intro_cta: 'Begynn sjekk',
      intro_scan: 'Skann strekkode',
      scan_new: 'Skann nytt produkt',
      reset: 'Nullstill',
      product_label: 'Valgt produkt',
      product_none: 'Ingen produkt valgt',
      product_high_risk: 'Dette produktet har høy risiko for forurensing.',
      product_hint: 'Skann strekkode eller skriv inn produktnavn.',
      we_assess: 'Vi vurderer',
      assess_origin: 'Opprinnelse og kjøpsland',
      assess_cert: 'Sertifisering og testprogrammer',
      assess_ingredients: 'Ingrediensliste og merking',
      assess_marketing: 'Markedsføring og produsent',
      step_of: (a: number, b: number) => `Spørsmål ${a} av ${b}`,
      yes: 'Ja', no: 'Nei', unsure: 'Usikker', next: 'Neste', back: 'Forrige',
      calculating: 'Beregner risiko',
      calc_sub: 'Vi vekter svarene dine mot WADAs prohibited list.',
      result_low_title: 'Lav risiko',
      result_low_sub: 'Produktet ser trygt ut å bruke. Følg anbefalt dose.',
      result_mid_title: 'Middels risiko',
      result_mid_sub: 'Vi anbefaler å bekrefte med ADNO før bruk.',
      result_high_title: 'Høy risiko',
      result_high_sub: 'Dette produktet bør unngås. Vi anbefaler å kontakte ADNO.',
      contact_adno: 'Kontakt ADNO for råd',
      new_check: 'Ny sjekk',
      save_result: 'Lagre til profilen',
      assessment_done: 'Vurdering fullført',
      warnings: 'Varselpunkter',
      notes: 'Merknader',
    },
    product: {
      title: 'Sjekk produkt',
      intro: 'Skriv inn strekkode eller produktnavn. Vi henter ingredienser fra Open Food Facts og krysser mot WADA 2026.',
      placeholder: 'Strekkode eller produktnavn',
      searching: 'Søker…',
      lookup_barcode: 'Slå opp strekkode',
      search_product: 'Søk produkt',
      web_hint_prefix: 'På mobil scanner appen strekkode med kameraet. Her i web-prototypen tester du ved å lime inn strekkode (f.eks. ',
      web_hint_suffix: ' for Nutella).',
      barcode_not_found: (b: string) => `Fant ikke strekkode ${b} i Open Food Facts.`,
      no_results_for: (q: string) => `Ingen treff på «${q}».`,
      off_unreachable: (msg: string) => `Kunne ikke nå Open Food Facts: ${msg}`,
      unknown_error: 'ukjent feil',
      results_count: (n: number) => `${n} treff`,
      unnamed: 'Uten navn',
      recent: 'Nylige søk',
      source_off_wada: 'KILDE · OPEN FOOD FACTS / WADA 2026',
      no_product_data: 'Ingen produktdata.',
      product_fallback: 'Produkt',
      no_wada_match: 'Ingen WADA-treff',
      banned_ingredient: 'Forbudt stoff i ingredienser',
      requires_tue: 'Krever fritak',
      banned_in_comp: 'Forbudt i konkurranse',
      allowed_note: 'Vi fant ingen treff fra dopinglisten i ingredienslisten. Sjekk likevel om produktet er Informed Sport-sertifisert.',
      found_matches: (n: number) => `Vi fant ${n} stoff${n === 1 ? '' : 'er'} som matcher WADA-listen. Se under.`,
      wada_matches: 'WADA-treff',
      ingredients: 'Ingredienser',
      no_ingredients: 'Open Food Facts har ikke ingrediensliste for dette produktet.',
      view_on_off: 'Se på Open Food Facts',
      disclaimer: 'Ansvar ligger hos utøveren · WADA 2026 · OFF',
    },
    meds: {
      title: 'Legemiddelsøk',
      placeholder: 'Søk på medisin eller virkestoff',
      empty_hint: 'Søk på navn (f.eks. Paracet), virkestoff eller reseptnummer.',
      source: 'Kilde · Felleskatalogen',
      status_allowed: 'Tillatt',
      status_banned: 'Forbudt',
      status_incomp: 'Forbudt i konkurranse',
      status_tue: 'Krever medisinsk fritak',
      send_confirm: 'Send bekreftelse til e-post',
      confirm_sent: 'Bekreftelse sendt',
      suggestions: 'Forslag',
      no_results_for: (q: string) => `Ingen treff på «${q}»`,
      details: 'Detaljer',
      active_ingredient: 'Virkestoff',
      manufacturer: 'Produsent',
      atc_code: 'ATC-kode',
      felleskatalogen: 'Felleskatalogen',
      full_monograph: 'Full preparatomtale',
      check_global_dro: 'Sjekk i Global DRO',
      pharma_label: 'Legemiddel',
    },
    wada: {
      title: 'Søk i dopinglista',
      tab_label: 'Dopinglisten',
      tab_meds: 'Legemidler',
      sub: 'WADA Prohibited List · Oppdatert 01.01.2026',
      placeholder: 'Søk på substans eller kategori',
      placeholder_substance: 'Søk på virkestoff eller kategori...',
      no_result: 'Ingen treff',
      no_result_sub: 'Vi fant ikke denne substansen. Send oss spørsmålet ditt.',
      ask_adno: 'Spør ADNOs medisinske rådgiver',
      category: 'WADA-kategori',
      popular: 'Populære søk',
      wada_categories: 'WADA-kategorier',
      no_match_title: 'Ingen treff i listen',
      no_match_sub: (q: string) => `Vi fant ikke «${q}» i den offisielle dopinglisten. Dette betyr ikke nødvendigvis at det er tillatt.`,
      ask_advisor: 'Spør en rådgiver',
      header_label: 'Wada Prohibited List 2026',
      resources: 'Ressurser',
      read_wada: 'Les WADA-dokumentasjon',
      read_wada_sub: 'wada-ama.org · Prohibited List 2026',
      cat_s0: 'S0 — Ikke-godkjente substanser',
      cat_s1: 'S1 — Anabole stoffer',
      cat_s2: 'S2 — Peptidhormoner',
      cat_s3: 'S3 — Beta-2-agonister',
      cat_s6: 'S6 — Stimulerende midler',
      cat_s8: 'S8 — Cannabinoider',
    },
    messages: {
      title: 'Meldinger',
      empty: 'Ingen nye meldinger',
      mark_read: 'Marker som lest',
      unread_suffix: 'uleste',
      all_read: 'Alt lest',
      loading: 'Henter varsler…',
      fetch_error: (e: string) => `Kunne ikke hente varsler: ${e}`,
      updated_from: 'OPPDATERES FRA ADNO + WADA',
      not_found: 'Fant ikke meldingen.',
      read_source: 'Les originalkilde',
      cat_urgent: 'Hastevarsel',
      cat_rule: 'Regelendring',
      cat_reminder: 'Påminnelse',
      cat_news: 'Nyhet',
    },
    asthma: {
      title: 'Astmakalkulator',
      sub: 'Sjekk tillatte doser for astmamedisiner.',
      select_med: 'Velg medisin',
      dose: 'Dose (µg)',
      frequency: 'Doser per døgn',
      calc: 'Beregn',
      allowed: 'Innenfor tillatt grense',
      allowed_sub: 'Du trenger ikke medisinsk fritak.',
      needs_tue: 'Krever medisinsk fritak',
      needs_tue_sub: 'Daglig dose overskrider WADAs grenseverdi.',
      goto_tue: 'Les om medisinsk fritak',
      daily_dose: 'Daglig dose',
    },
    tue: {
      title: 'Medisinsk fritak',
      sub: 'Veileder for deg som trenger å bruke forbudt substans av medisinske grunner.',
      part: 'DEL',
      sec1_title: 'Hvem trenger fritak?',
      sec1_body: 'Utøvere som må bruke en substans eller metode som står på dopinglisten av medisinske grunner.',
      sec2_title: 'Hvordan søker jeg?',
      sec2_body: 'Fyll ut søknadsskjema sammen med legen din. Send til ADNO senest 30 dager før konkurranse.',
      sec3_title: 'Skjemaer og veiledning',
      sec3_body: 'Offisielle skjemaer fra Antidoping Norge og WADA.',
      sec4_title: 'Frister',
      sec4_body: 'Nasjonalt nivå: 30 dager før. Internasjonalt: kontakt ditt særforbund.',
      res_no: 'Søknadsskjema TUE (norsk)',
      res_wada: 'WADA TUE Application Form (engelsk)',
      res_istue: 'Internasjonale standarder for fritak (ISTUE)',
    },
    report: {
      title: 'Dopingvarsel',
      sub: 'Varsle om brudd — helt anonymt hvis du ønsker.',
      body: 'Varslingskanalen driftes eksternt av Whistleblower Network. Du kan varsle helt anonymt.',
      cta: 'Gå til anonymt varsel',
      secure: 'Sikker forbindelse',
    },
    contact: {
      title: 'Kontakt oss',
      chat_open: 'Chatten er åpen',
      chat_closed: 'Chatten er stengt · Send beskjed',
      hours: 'Mandag–fredag · 09–15',
      form_name: 'Navn',
      form_email: 'E-post',
      form_message: 'Hva kan vi hjelpe med?',
      send: 'Send melding',
      adno_advisor: 'ADNO RÅDGIVER',
    },
    settings: {
      title: 'Innstillinger',
      profile: 'Profil', push: 'Varsler', privacy: 'Personvern',
      language: 'Språk', about: 'Om appen', signout: 'Logg ut',
      version: 'Versjon 1.0 (beta)',
      preferences: 'Preferanser',
      privacy_data: 'Personvern og data',
      dark_mode: 'Mørk modus',
      privacy_policy: 'Personvernerklæring',
      privacy_policy_sub: 'WADA ISPPPI-kompatibel · antidoping.no',
      download_data: 'Last ned mine data',
      download_data_sub: 'JSON-eksport av alt appen har lagret om deg',
      send_test: 'Send testvarsel',
      send_test_sub: 'Verifiser at varsler fungerer på enheten din',
      push_active: 'Aktive · Hastevarsler og regelendringer',
      push_blocked: 'Blokkert i nettleseren — endre i sideinnstillinger',
      push_unsupported: 'Krever native bygg (iOS/Android)',
      push_default: 'Hastevarsler, regelendringer, nyheter',
      role_athlete: 'Utøver',
      push_enabled_title: 'Push-varsler aktivert',
      push_enabled_body: 'Du får varsel ved hastevarsel og regelendringer fra ADNO.',
      test_title: 'Antidoping Norge · Hastevarsel',
      test_body: 'Pure Mass XL fra musclezone.com testet positivt for stanozolol. Slutt å bruke umiddelbart.',
      push_alert_title: 'Push-varsler',
      push_alert_body: 'Aktiver push-varsler først, og gi nettleseren tillatelse.',
      my_data: 'Mine data',
      signout_confirm_title: 'Logg ut',
      signout_confirm: 'Er du sikker på at du vil logge ut? All lagret data slettes.',
      signout_confirm_short: 'Er du sikker? All lagret data slettes.',
      org_footer: 'ANTIDOPING NORGE',
    },
    chat: {
      title: 'Spør ADNO',
      clear: 'Tøm',
      placeholder: 'Skriv et spørsmål…',
      advisor: 'AI-rådgiver',
      advisor_sub: 'Bygget på WADA 2026 + ADNO-veiledning',
      intro: 'Spør om legemidler, fritak, kosttilskudd eller WADA-regler. Jeg svarer basert på offisiell informasjon, men endelig ansvar ligger hos deg.',
      suggestions: 'FORSLAG',
      thinking: 'tenker…',
      disclaimer: 'AI-GENERERT · DOBBELTSJEKK MED ADNO VED TVIL',
      q_paracet: 'Kan jeg ta Paracet før konkurranse?',
      q_ventoline: 'Hvor mye Ventoline kan jeg bruke per døgn?',
      q_ritalin: 'Trenger jeg fritak for Ritalin?',
      q_supplement: 'Hvordan vurderer jeg risiko ved kosttilskudd?',
      reply_paracet: 'Paracet (paracetamol) står ikke på WADAs prohibited list og kan trygt brukes både i og utenfor konkurranse. Følg anbefalt dose på pakningen.',
      reply_ventoline: 'Salbutamol (Ventoline) er tillatt i inhalert form opptil 600 µg per 8 timer og 1600 µg per døgn (WADA 2026). Doser over dette krever medisinsk fritak.',
      reply_ritalin: 'Metylfenidat (Ritalin) er forbudt i konkurranse (S6 Stimulerende midler). Du må ha innvilget medisinsk fritak før konkurranse.',
      reply_supplement: 'Bruk Risikosjekk-funksjonen i appen, og sjekk om produktet er Informed Sport-sertifisert. Om mulig velg apotekkjøp i Norge fra leverandører med batch-testing.',
      reply_default: 'Takk for spørsmålet. Generelt råd: sjekk legemidler i Felleskatalogen + dopinglisten, og kontakt ADNOs medisinske rådgiver direkte ved tvil. Ansvar for hva som inntas ligger alltid hos utøveren.',
    },
    learn: {
      title: 'Ren Utøver',
      sub: 'Offisiell e-læring fra Antidoping Norge. Ca. 110 minutter totalt.',
      source: 'KILDE · ANTIDOPING NORGE / RENUTOVER.NO',
      c01_title: 'Grunnkurs Ren Utøver',
      c01_sub: '6 moduler · 45 min',
      c02_title: 'Kosttilskudd og risiko',
      c02_sub: '3 moduler · 20 min',
      c03_title: 'Whereabouts',
      c03_sub: '4 moduler · 30 min',
      c04_title: 'Medisinsk fritak',
      c04_sub: '2 moduler · 15 min',
    },
  },
  en: null as any,
};

STRINGS.en = {
  ...STRINGS.nb,
  appName: 'Antidoping',
  tagline: 'in your pocket',
  home_hello: 'Hi, Emma',
  home_sub: 'What can we help with today?',
  home_org: 'Antidoping Norge',
  home_quote: '"Check first. Compete clean."',
  home_features: {
    risk: 'Supplements',
    medicine: 'Medicines',
    wada: 'Prohibited list',
    messages: 'Alerts',
    learn: 'Clean Athlete',
    exemption: 'TUE',
    asthma: 'Asthma',
    report: 'Report',
    contact: 'Ask ADNO',
  },
  common: {
    get_started: 'Get started',
    next: 'Next',
    finish: 'Finish',
    cancel: 'Cancel',
    ok: 'OK',
  },
  onboard: {
    welcome_title: 'Welcome to Antidoping',
    welcome_sub: 'Everything you need to make safe choices — in one place.',
    continue: 'Get started',
    role_title: 'Who are you?',
    role_sub: 'We tailor the content to your role.',
    role_athlete: 'Athlete',
    role_athlete_sub: 'Competition or recreational',
    role_coach: 'Coach / support personnel',
    role_coach_sub: 'Responsible for other athletes',
    role_parent: 'Parent / guardian',
    role_parent_sub: 'Parent or legal guardian',
    consent_title: 'Notifications and privacy',
    consent_sub: 'You can disable each category later.',
    consent_push: 'Important alerts from ADNO',
    consent_push_sub: 'Rule changes and urgent alerts',
    consent_privacy: 'I accept the privacy policy',
    consent_privacy_sub: 'WADA ISPPPI-compliant · Read more',
    finish: 'Done',
  },
  risk: {
    intro_title: 'Check a supplement',
    intro_sub: 'Answer 8 short questions. We give you a risk score in under a minute.',
    intro_cta: 'Start check',
    intro_scan: 'Scan barcode',
    scan_new: 'Scan new product',
    reset: 'Reset',
    product_label: 'Selected product',
    product_none: 'No product selected',
    product_high_risk: 'This product has a high contamination risk.',
    product_hint: 'Scan a barcode or enter a product name.',
    we_assess: 'We assess',
    assess_origin: 'Origin and country of purchase',
    assess_cert: 'Certification and testing programs',
    assess_ingredients: 'Ingredient list and labeling',
    assess_marketing: 'Marketing and manufacturer',
    step_of: (a: number, b: number) => `Question ${a} of ${b}`,
    yes: 'Yes', no: 'No', unsure: 'Not sure', next: 'Next', back: 'Back',
    calculating: 'Calculating risk',
    calc_sub: 'We weigh your answers against the WADA Prohibited List.',
    result_low_title: 'Low risk',
    result_low_sub: 'The product looks safe to use. Follow recommended dosage.',
    result_mid_title: 'Medium risk',
    result_mid_sub: 'We recommend confirming with ADNO before use.',
    result_high_title: 'High risk',
    result_high_sub: 'This product should be avoided. We recommend contacting ADNO.',
    contact_adno: 'Contact ADNO for advice',
    new_check: 'New check',
    save_result: 'Save to profile',
    assessment_done: 'Assessment complete',
    warnings: 'Warning points',
    notes: 'Notes',
  },
  product: {
    title: 'Check product',
    intro: 'Enter a barcode or product name. We fetch ingredients from Open Food Facts and cross-check against WADA 2026.',
    placeholder: 'Barcode or product name',
    searching: 'Searching…',
    lookup_barcode: 'Look up barcode',
    search_product: 'Search product',
    web_hint_prefix: 'On mobile the app scans barcodes with the camera. In this web prototype you can test by pasting a barcode (e.g. ',
    web_hint_suffix: ' for Nutella).',
    barcode_not_found: (b: string) => `Barcode ${b} not found in Open Food Facts.`,
    no_results_for: (q: string) => `No results for "${q}".`,
    off_unreachable: (msg: string) => `Could not reach Open Food Facts: ${msg}`,
    unknown_error: 'unknown error',
    results_count: (n: number) => `${n} results`,
    unnamed: 'Unnamed',
    recent: 'Recent searches',
    source_off_wada: 'SOURCE · OPEN FOOD FACTS / WADA 2026',
    no_product_data: 'No product data.',
    product_fallback: 'Product',
    no_wada_match: 'No WADA matches',
    banned_ingredient: 'Prohibited substance in ingredients',
    requires_tue: 'Requires TUE',
    banned_in_comp: 'Prohibited in competition',
    allowed_note: 'We found no matches from the Prohibited List in the ingredients. Still verify that the product is Informed Sport certified.',
    found_matches: (n: number) => `We found ${n} substance${n === 1 ? '' : 's'} matching the WADA list. See below.`,
    wada_matches: 'WADA matches',
    ingredients: 'Ingredients',
    no_ingredients: 'Open Food Facts has no ingredient list for this product.',
    view_on_off: 'View on Open Food Facts',
    disclaimer: 'Responsibility lies with the athlete · WADA 2026 · OFF',
  },
  meds: {
    title: 'Medicine search',
    placeholder: 'Search medicine or active ingredient',
    empty_hint: 'Search by name (e.g. Paracet), active ingredient or prescription number.',
    source: 'Source · Felleskatalogen',
    status_allowed: 'Allowed',
    status_banned: 'Prohibited',
    status_incomp: 'Prohibited in competition',
    status_tue: 'Requires TUE',
    send_confirm: 'Send confirmation to email',
    confirm_sent: 'Confirmation sent',
    suggestions: 'Suggestions',
    no_results_for: (q: string) => `No results for "${q}"`,
    details: 'Details',
    active_ingredient: 'Active ingredient',
    manufacturer: 'Manufacturer',
    atc_code: 'ATC code',
    felleskatalogen: 'Felleskatalogen',
    full_monograph: 'Full monograph',
    check_global_dro: 'Check in Global DRO',
    pharma_label: 'Medicine',
  },
  wada: {
    title: 'Search the Prohibited List',
    tab_label: 'Prohibited List',
    tab_meds: 'Medicines',
    sub: 'WADA Prohibited List · Updated 01/01/2026',
    placeholder: 'Search substance or category',
    placeholder_substance: 'Search active ingredient or category...',
    no_result: 'No results',
    no_result_sub: 'We could not find this substance. Send us your question.',
    ask_adno: "Ask ADNO's medical advisor",
    category: 'WADA category',
    popular: 'Popular searches',
    wada_categories: 'WADA categories',
    no_match_title: 'No match in the list',
    no_match_sub: (q: string) => `We could not find "${q}" in the official Prohibited List. This does not necessarily mean it is allowed.`,
    ask_advisor: 'Ask an advisor',
    header_label: 'WADA Prohibited List 2026',
    resources: 'Resources',
    read_wada: 'Read WADA documentation',
    read_wada_sub: 'wada-ama.org · Prohibited List 2026',
    cat_s0: 'S0 — Non-approved substances',
    cat_s1: 'S1 — Anabolic agents',
    cat_s2: 'S2 — Peptide hormones',
    cat_s3: 'S3 — Beta-2 agonists',
    cat_s6: 'S6 — Stimulants',
    cat_s8: 'S8 — Cannabinoids',
  },
  messages: {
    title: 'Alerts',
    empty: 'No new alerts',
    mark_read: 'Mark as read',
    unread_suffix: 'unread',
    all_read: 'All read',
    loading: 'Fetching alerts…',
    fetch_error: (e: string) => `Could not fetch alerts: ${e}`,
    updated_from: 'UPDATED FROM ADNO + WADA',
    not_found: 'Message not found.',
    read_source: 'Read original source',
    cat_urgent: 'Urgent alert',
    cat_rule: 'Rule change',
    cat_reminder: 'Reminder',
    cat_news: 'News',
  },
  asthma: {
    title: 'Asthma calculator',
    sub: 'Check allowed doses for asthma medications.',
    select_med: 'Select medicine',
    dose: 'Dose (µg)',
    frequency: 'Doses per 24h',
    calc: 'Calculate',
    allowed: 'Within allowed limit',
    allowed_sub: 'You do not need a TUE.',
    needs_tue: 'Requires TUE',
    needs_tue_sub: 'Daily dose exceeds the WADA threshold.',
    goto_tue: 'Read about TUE',
    daily_dose: 'Daily dose',
  },
  tue: {
    title: 'Therapeutic Use Exemption (TUE)',
    sub: 'Guide for those who need to use a prohibited substance for medical reasons.',
    part: 'PART',
    sec1_title: 'Who needs a TUE?',
    sec1_body: 'Athletes who must use a substance or method on the Prohibited List for medical reasons.',
    sec2_title: 'How do I apply?',
    sec2_body: 'Complete the application form together with your doctor. Submit to ADNO at least 30 days before competition.',
    sec3_title: 'Forms and guidance',
    sec3_body: 'Official forms from Antidoping Norge and WADA.',
    sec4_title: 'Deadlines',
    sec4_body: 'National level: 30 days before. International: contact your federation.',
    res_no: 'TUE Application Form (Norwegian)',
    res_wada: 'WADA TUE Application Form (English)',
    res_istue: 'International Standard for TUEs (ISTUE)',
  },
  report: {
    title: 'Doping report',
    sub: 'Report violations — completely anonymous if you wish.',
    body: 'The reporting channel is operated externally by Whistleblower Network. You can report fully anonymously.',
    cta: 'Go to anonymous report',
    secure: 'Secure connection',
  },
  contact: {
    title: 'Contact us',
    chat_open: 'Chat is open',
    chat_closed: 'Chat is closed · Send a message',
    hours: 'Monday–Friday · 09–15',
    form_name: 'Name',
    form_email: 'Email',
    form_message: 'How can we help?',
    send: 'Send message',
    adno_advisor: 'ADNO ADVISOR',
  },
  settings: {
    title: 'Settings',
    profile: 'Profile', push: 'Notifications', privacy: 'Privacy',
    language: 'Language', about: 'About', signout: 'Sign out',
    version: 'Version 1.0 (beta)',
    preferences: 'Preferences',
    privacy_data: 'Privacy and data',
    dark_mode: 'Dark mode',
    privacy_policy: 'Privacy policy',
    privacy_policy_sub: 'WADA ISPPPI-compliant · antidoping.no',
    download_data: 'Download my data',
    download_data_sub: 'JSON export of everything the app has stored about you',
    send_test: 'Send test notification',
    send_test_sub: 'Verify that notifications work on your device',
    push_active: 'Active · Urgent alerts and rule changes',
    push_blocked: 'Blocked in the browser — change in site settings',
    push_unsupported: 'Requires native build (iOS/Android)',
    push_default: 'Urgent alerts, rule changes, news',
    role_athlete: 'Athlete',
    push_enabled_title: 'Push notifications enabled',
    push_enabled_body: 'You will receive urgent alerts and rule-change notifications from ADNO.',
    test_title: 'Antidoping Norge · Urgent alert',
    test_body: 'Pure Mass XL from musclezone.com tested positive for stanozolol. Stop use immediately.',
    push_alert_title: 'Push notifications',
    push_alert_body: 'Enable push notifications first, and grant the browser permission.',
    my_data: 'My data',
    signout_confirm_title: 'Sign out',
    signout_confirm: 'Are you sure you want to sign out? All stored data will be deleted.',
    signout_confirm_short: 'Are you sure? All stored data will be deleted.',
    org_footer: 'ANTIDOPING NORGE',
  },
  chat: {
    title: 'Ask ADNO',
    clear: 'Clear',
    placeholder: 'Type a question…',
    advisor: 'AI advisor',
    advisor_sub: 'Built on WADA 2026 + ADNO guidance',
    intro: 'Ask about medicines, exemptions, supplements or WADA rules. I answer based on official information, but final responsibility is yours.',
    suggestions: 'SUGGESTIONS',
    thinking: 'thinking…',
    disclaimer: 'AI-GENERATED · DOUBLE-CHECK WITH ADNO IF IN DOUBT',
    q_paracet: 'Can I take Paracet before competition?',
    q_ventoline: 'How much Ventoline can I use per 24 hours?',
    q_ritalin: 'Do I need a TUE for Ritalin?',
    q_supplement: 'How do I assess risk for supplements?',
    reply_paracet: 'Paracet (paracetamol) is not on the WADA Prohibited List and can be used safely both in and out of competition. Follow the recommended dose on the package.',
    reply_ventoline: 'Salbutamol (Ventoline) is allowed in inhaled form up to 600 µg per 8 hours and 1600 µg per 24 hours (WADA 2026). Doses above this require a TUE.',
    reply_ritalin: 'Methylphenidate (Ritalin) is prohibited in competition (S6 Stimulants). You must have an approved TUE before competing.',
    reply_supplement: 'Use the Risk check feature in the app, and verify whether the product is Informed Sport certified. When possible buy from Norwegian pharmacies with suppliers that batch-test.',
    reply_default: 'Thanks for the question. General advice: check medicines in Felleskatalogen + the Prohibited List, and contact ADNO\'s medical advisor directly if in doubt. Responsibility for what is ingested always lies with the athlete.',
  },
  learn: {
    title: 'Clean Athlete',
    sub: 'Official e-learning from Antidoping Norge. Approx. 110 minutes total.',
    source: 'SOURCE · ANTIDOPING NORGE / RENUTOVER.NO',
    c01_title: 'Clean Athlete foundation course',
    c01_sub: '6 modules · 45 min',
    c02_title: 'Supplements and risk',
    c02_sub: '3 modules · 20 min',
    c03_title: 'Whereabouts',
    c03_sub: '4 modules · 30 min',
    c04_title: 'Therapeutic Use Exemption',
    c04_sub: '2 modules · 15 min',
  },
};

export const T = (lang: Lang) => STRINGS[lang] || STRINGS.nb;
